export const defaultItems = [
    {
        _id: '',
        title: '',
        description: '',
        image: 'kikugahama.jpg',
        category: '',
        isDefault: true,
        defaultAlt: 'Kikugahama',
    },
    {
        _id: '',
        title: '',
        description: '',
        image: 'kikuya.jpg',
        category: '',
        isDefault: true,
        defaultAlt: 'Kikuya',
    },

    {
        _id: '',
        title: '',
        description: '',
        image: 'mealset.jpg',
        category: '',
        isDefault: true,
        defaultAlt: 'Meal set',
    },
    {
        _id: '',
        title: '',
        description: '',
        image: 'bantokai.jpg',
        category: '',
        isDefault: true,
        defaultAlt: 'Bantokai',
    },
    {
        _id: '',
        title: '',
        description: '',
        image: 'ship.jpg',
        category: '',
        isDefault: true,
        defaultAlt: 'Ship',
    },
    {
        _id: '',
        title: '',
        description: '',
        image: 'kasayama.jpg',
        category: '',
        isDefault: true,
        defaultAlt: 'Kasayama',
    },
    {
        _id: '',
        title: '',
        description: '',
        image: 'storage.jpg',
        category: '',
        isDefault: true,
        defaultAlt: 'storage',
    },
    {
        _id: '',
        title: '',
        description: '',
        image: 'tsubaki.jpg',
        category: '',
        isDefault: true,
        defaultAlt: 'tsubaki',
    },
    {
        _id: '',
        title: '',
        description: '',
        image: 'amadai.jpg',
        category: '',
        isDefault: true,
        defaultAlt: 'Amadai',
    },
];
